### ISSUE TITLE
Azure DevOps Project Creation

### ISSUE THREAD

**Issue by rpothin** [rpothin/coe-starter-kit#6]
## Task to automate

Azure DevOps Project Creation

## Description

Create an Azure DevOps project if it does not exist.

## Corresponding section in the GETTINGSTARTED.md procedure

- [Copy the YAML Pipelines from GitHub to your Azure DevOps instance](https://github.com/microsoft/coe-starter-kit/blob/main/PowerPlatformDevOpsALM/GETTINGSTARTED.md#copy-the-yaml-pipelines-from-github-to-your-azure-devops-instance)
- [Update Permissions for the Project Build Service](https://github.com/microsoft/coe-starter-kit/blob/main/PowerPlatformDevOpsALM/GETTINGSTARTED.md#update-permissions-for-the-project-build-service)

## Permissions needed

The fact that you will be able to complete or not this task will depend on the permissions the account you use have on the considered Azure DevOps organization - [Set permissions at the project- or collection-level](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-project-collection-level-permissions?view=azure-devops&tabs=preview-page)

> *One example we can follow address this requirement is the following one: [Scaffolding/DevOps/projectSetUp.ps1](https://github.com/Azure/azure-devops-cli-extension/blob/master/examples/Scaffolding/DevOps/projectSetUp.ps1)*

## PowerShell module(s) / command(s)

- Module: [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli#install-or-update)
- Commands:
   - [az devops project show](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/project?view=azure-cli-latest#ext_azure_devops_az_devops_project_show) to verify if the project exist
   - [az devops project create](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/project?view=azure-cli-latest#ext_azure_devops_az_devops_project_create) to create the project

## Input parameters

- Azure DevOps organization URL
- Project Name

- [x] Configuration file for characteristics we want to apply to all the Azure DevOps projects (*ex: Source Control, Process, Visibility...*)

## Output parameters

- All the information of the Azure DevOps project created

**Comment by rpothin** [comment]
- [x] PowerShell function creation
- [x] Tests creation
- [ ] README update
- [ ] Pull request creation
